name = "cf-nuxt-pages-kit"
compatibility_date = "2024-12-01"
pages_build_output_dir = ".output/public"

[vars]
CDN_BASE_URL = "https://cdn.example.com"
RECORDING_JWT_SECRET = "test-secret-change-me"
JWT_KID = "primary"
JWT_ISSUER = "https://cf-nuxt-pages-kit.pages.dev"
PASSWORD_PEPPER = "change-me"
ACCESS_TOKEN_TTL_SECONDS = "600"
REFRESH_TOKEN_TTL_SECONDS = "1209600"
JWT_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUarQb1GjUtro8
RIJYgp2eFb31bqSA8Xhgd3vwa3KiCU0nNCT6Dhc684IW1bP90kFEV4e6ZFncMa+g
uWhUXudrZNFqGwUn6IAHtSXAytH+SL2CW+KZkO03YrUo9uhR0oZXd1/HjGPaQNcG
zsxTxlnaM0jVxK/+s/GTqvkB3H40A1bLfEX621XtMW5T9zDbdeCaT3Rx7cq2R0t0
pPHJL1NTfF3UKWcMHyBeduhyaufXAfznmv6/5ZyavnTLqX+xG7L6iDPkQfiTRxtl
MG8zlWN/9NMgcuGNJt7M0F2rtBgXE2n6xitSUXMsTjnV8CbAmQTRDC56qe3SRNnm
2F2YSYn1AgMBAAECggEAFUr68f05YvVMNuVhMZEqTqH8UEF+kQRjnjvr+x4yOAb5
qm/iMwS9lGW7iSFz8QImE704eFk93sJGSjS7vhVjWlMZYOsDecwnJV6lwa0zHqvY
/1vJm7444T/uTARwJl+Voufu/HhYvBSa2W5ach1kfWh9qRwVzlDoavaNDoA1UG5E
ZrHiATmShY9BgxPMjq06XpEkoeRawIa+RLWaFids6RVQ7F5GaxdCWo6u7yQ2bV9k
mKKzDZRb2RdBfom2KjDrhNWuRUYMh7U1JXN/RiXNWO9vyY0Uv9iBZjBtQNktG98s
LDHdsSRtv4PqXEt/6poTkSjAM/C9rJgBQ590k2QW0wKBgQD5OOon5SRpX/WXM7mN
rCXP9uQJrBdKjPgKI1mRt7XIDRDWG0FKWfbBpyhrzCK5YX7BD+/nUWC2ay4AY1vC
CN9WZYsZGaRmMZfT5IF28y3+GnKk0BSFCwe2arBIr3uVwg6PwPxSawDbZI03u2SJ
6VsYlF4miLfX1T+kbubyZxQfJwKBgQDaMYyJjeODZDqIOOozqNK+A8lwYgCjjIWu
kOoofW9e8t0pFNgG0hXD01e0AqZYSa5Bbuky+KABE13t7+J5QLHShy+uU3BlZw2R
ZjL8AZ+ghWmGZsfCCsq5YCAQkjYOSJ290sF0P792BEjHBSNOguBko4r3Gn52p6Jz
Ok6BY/U/gwKBgEoZ0BV4njDupTkF2h/zlXKWOAtgLbSu4XkyNYmME/KdX+opRGp1
AVdm+i/DDHgOMv/4Wx5uJdFXYOAgqsGwnac0nf0ikK0KBdis0ompmH07I+c5L0C3
nN1yL2QNOTO39Vhsyxk+U4zoAs0VXLlctwdB5hSTBgaYk0my59wfJe51AoGBAL9n
C9N2xofyGm55Dum2RPgutjyBm/HcSUCzGtXeAx6ViXCKOl7xV+pqsNrWIDn+mIAJ
3UO7WhDXfmRFNLQNDnCR6j/QLh6l4f8UWdE7U14q6kDeVIlhkig/rKEcwZKSHN3x
zYY+jaPnajg7x5cNs+5UkIjnktxffV/7W/ahSvglAoGBAJHJ8u+uLgEnz6BfnLjm
1aI4UA84P7vV86DITOqQhvLUB7NSdovS1icZt2NE8okxAbEZ6blIwPDZT8YI6ZvX
n5/X3m93AJzSN1lIgqWScvq+jYzJ3UNDHpOv+zfspo1JIN0QGiXIEBEFeR7rImGa
5xtc2vq6K9M8eRsW2yPYRupa
-----END PRIVATE KEY-----
"""

[[d1_databases]]
binding = "DB"
database_name = "cf-nuxt-pages-db"
database_id = "f2face1e-57b8-41ee-9ca5-9447212444d5"
